### PR TITLE
add rename feature to Duplicate

### PR DESCRIPTION
**Pull request by BasilYes**
Add rename feature to Duplicate

### CODE REVIEW

**Comment by MakovWait** [comment]
Hey! Looks pretty good, but we already have the similar feature that is called 'Duplicate'. Any reason why we need one more similar possibility?

**Comment by BasilYes** [comment]
I think now it's very similar, so it's have not many sense now. (Be honest I did it cause I didn't know about duplicate) But when I creating it, I got some ideas in mind to upgrade it to something unique (like .tamplateignore similar to .gitignore). So I move it to draft

**Comment by BasilYes** [comment]
And Duplicate don't change project name (notice it's after test Duplicate). ^_^

**Comment by MakovWait** [comment]
I think we can apply the idea to 'Duplicate'. For instance, add a checkbox for overriding the name and add something like '.duplicate-ignore' or stuff. What do you think?

**Comment by BasilYes** [comment]
> I think we can apply the idea to 'Duplicate'. For instance, add a checkbox for overriding the name and add something like '.duplicate-ignore' or stuff. What do you think?

Yes, I understand. Create similar features is bad idea. I will move this functionality to Duplicate.

**Comment by MakovWait** [comment]
Thanks!

**Pull request merged**
