### PR TITLE
add ability to select icon.svg in settings

### PR DESCRIPTION
**Pull request by BasilYes**
Add ability to select icon.svg inside new project instead of icon.png #61

### CODE REVIEW

**Comment by MakovWait** [comment]
This will not work in export builds:
```gdscript
DirAccess.copy_absolute("res://assets/default_project_icon.svg", dir.path_join("icon.svg"))
```
seems like there is some [workaround](https://forum.godotengine.org/t/how-to-access-a-file-from-res-in-the-exported-project/3273/2). 

I'm not sure if global settings is where you should put the checkbox: I think the better place is to put it in the new project dialog.

**Comment by BasilYes** [comment]
> This will not work in export builds:
> 
> ```gdscript
> DirAccess.copy_absolute("res://assets/default_project_icon.svg", dir.path_join("icon.svg"))
> ```
> 
> seems like there is some [workaround](https://forum.godotengine.org/t/how-to-access-a-file-from-res-in-the-exported-project/3273/2).
Thanks, I don't noticed this. But this workaround didn't work too, so I done another workaround and it's work.

> I'm not sure if global settings is where you should put the checkbox: I think the better place is to put it in the new project dialog.

Yes, it's will be better.

**Comment by BasilYes** [comment]
May be Godots should remember your choose, but I'm not sure how to implement this properly.

**Comment by MakovWait** [comment]
> May be Godots should remember user choose (.svg or .png), but I'm not sure how to implement this properly.

for this we use [cache](https://github.com/MakovWait/godots/blob/main/src/cache.gd)
for instance: https://github.com/MakovWait/godots/blob/cf4b11bba4cbd597ad32885b29a1f1b29b80cb06/src/components/editors/remote/remote_editors.gd#L23-L24

So it may look like:
```gdscript
var use_png = Cache.smart_value(self, "use_png", true)

use_png.ret()
use_png.put(new_val)
```

**Comment by BasilYes** [comment]
Done

**Comment by MakovWait** [comment]
Cool thanks!

**Pull request merged**
